Name= input("Enter your Name: ")
Gender= input("Tell me your Gender: ")
Branch = input("What is your Branch: ")
College= input("What's your College Name: ")
Age= int(input("Enter your Age: "))
print("Name:",name)
print("Gender:",Gender)
print("Branch:",Branch)
print("College Name:",College)
print("Age:",Age)
